//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuantic.Core.Date {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eQuantic.Core.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CHY{0}.
        /// </summary>
        public static string CalendarHalfyearName {
            get {
                return ResourceManager.GetString("CalendarHalfyearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CHY{0} {1}.
        /// </summary>
        public static string CalendarHalfyearOfYearName {
            get {
                return ResourceManager.GetString("CalendarHalfyearOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CQ{0}.
        /// </summary>
        public static string CalendarQuarterName {
            get {
                return ResourceManager.GetString("CalendarQuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CQ{0} {1}.
        /// </summary>
        public static string CalendarQuarterOfYearName {
            get {
                return ResourceManager.GetString("CalendarQuarterOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to CY{0}.
        /// </summary>
        public static string CalendarYearName {
            get {
                return ResourceManager.GetString("CalendarYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FHY{0}.
        /// </summary>
        public static string FiscalHalfyearName {
            get {
                return ResourceManager.GetString("FiscalHalfyearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FHY{0} {1}.
        /// </summary>
        public static string FiscalHalfyearOfYearName {
            get {
                return ResourceManager.GetString("FiscalHalfyearOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FQ{0}.
        /// </summary>
        public static string FiscalQuarterName {
            get {
                return ResourceManager.GetString("FiscalQuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FQ{0} {1}.
        /// </summary>
        public static string FiscalQuarterOfYearName {
            get {
                return ResourceManager.GetString("FiscalQuarterOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FY{0}.
        /// </summary>
        public static string FiscalYearName {
            get {
                return ResourceManager.GetString("FiscalYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string MonthOfYearName {
            get {
                return ResourceManager.GetString("MonthOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SHY{0}.
        /// </summary>
        public static string SchoolHalfyearName {
            get {
                return ResourceManager.GetString("SchoolHalfyearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SHY{0} {1}.
        /// </summary>
        public static string SchoolHalfyearOfYearName {
            get {
                return ResourceManager.GetString("SchoolHalfyearOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SQ{0}.
        /// </summary>
        public static string SchoolQuarterName {
            get {
                return ResourceManager.GetString("SchoolQuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SQ{0} {1}.
        /// </summary>
        public static string SchoolQuarterOfYearName {
            get {
                return ResourceManager.GetString("SchoolQuarterOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SY{0}.
        /// </summary>
        public static string SchoolYearName {
            get {
                return ResourceManager.GetString("SchoolYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to HY{0}.
        /// </summary>
        public static string SystemHalfyearName {
            get {
                return ResourceManager.GetString("SystemHalfyearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to HY{0} {1}.
        /// </summary>
        public static string SystemHalfyearOfYearName {
            get {
                return ResourceManager.GetString("SystemHalfyearOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Q{0}.
        /// </summary>
        public static string SystemQuarterName {
            get {
                return ResourceManager.GetString("SystemQuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Q{0} {1}.
        /// </summary>
        public static string SystemQuarterOfYearName {
            get {
                return ResourceManager.GetString("SystemQuarterOfYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}.
        /// </summary>
        public static string SystemYearName {
            get {
                return ResourceManager.GetString("SystemYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Day.
        /// </summary>
        public static string TimeSpanDay {
            get {
                return ResourceManager.GetString("TimeSpanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Days.
        /// </summary>
        public static string TimeSpanDays {
            get {
                return ResourceManager.GetString("TimeSpanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hour.
        /// </summary>
        public static string TimeSpanHour {
            get {
                return ResourceManager.GetString("TimeSpanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hours.
        /// </summary>
        public static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Min.
        /// </summary>
        public static string TimeSpanMinute {
            get {
                return ResourceManager.GetString("TimeSpanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Mins.
        /// </summary>
        public static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Month.
        /// </summary>
        public static string TimeSpanMonth {
            get {
                return ResourceManager.GetString("TimeSpanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Months.
        /// </summary>
        public static string TimeSpanMonths {
            get {
                return ResourceManager.GetString("TimeSpanMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sec.
        /// </summary>
        public static string TimeSpanSecond {
            get {
                return ResourceManager.GetString("TimeSpanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Secs.
        /// </summary>
        public static string TimeSpanSeconds {
            get {
                return ResourceManager.GetString("TimeSpanSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Week.
        /// </summary>
        public static string TimeSpanWeek {
            get {
                return ResourceManager.GetString("TimeSpanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Weeks.
        /// </summary>
        public static string TimeSpanWeeks {
            get {
                return ResourceManager.GetString("TimeSpanWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Year.
        /// </summary>
        public static string TimeSpanYear {
            get {
                return ResourceManager.GetString("TimeSpanYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Years.
        /// </summary>
        public static string TimeSpanYears {
            get {
                return ResourceManager.GetString("TimeSpanYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to w/c {0} {1}.
        /// </summary>
        public static string WeekOfYearName {
            get {
                return ResourceManager.GetString("WeekOfYearName", resourceCulture);
            }
        }
    }
}
